### ISSUE TITLE
Error when executing elaChain

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.ORG.API.Misc#3]
```
time: invalid duration
```

**Comment by xiaomingfuckeasylife** [comment]
oh , I forget to update the readme as well . try it again.  @kpachhai  thanks for your feed back

**Comment by kpachhai** [comment]
Do we have plans on creating a documentation for all the API endpoints for this repo like wallet service and DID service?

**Comment by xiaomingfuckeasylife** [comment]
yes, we will do that in recent weeks.

**Comment by kpachhai** [comment]
Sounds good. Thanks :)
