### ISSUE TITLE
DPoS producer rank list doesn't return historical data based on block height

### ISSUE THREAD

**Issue by racollette** [elastos/Elastos.ORG.API.Misc#5]
The misc API command `/api/1/dpos/rank/height/(int:`height`)` returns the most recent producer rank list, regardless of what block height is entered.

The other command that uses block height `/api/1/dpos/vote/height/(int:`height`)`, however, functions as intended.

Historical block heights for the producer rank list would be a useful feature to help us with some tracking metrics.

Thank you,

Ryan

**Comment by xiaomingfuckeasylife** [comment]
hi , @racollette . the data looks all right to me. 
for example :
> https://api-wallet-ela.elastos.org/api/1/dpos/rank/height/414007 
>> {
  "result": [
    {
      "Producer_public_key": "0205a250b3a96ccc776604fafb84b0f8623fdfda6ec8f42c9154aa727bd95edfe2",
      "Value": "2247622.73145719",
      "Address": "EbHybMnexCbEEY4HHzxsVtZDZhzpSmShtd",
      "Rank": 1,
      "Ownerpublickey": "0205a250b3a96ccc776604fafb84b0f8623fdfda6ec8f42c9154aa727bd95edfe2",
      "Nodepublickey": "02caa563eab1cb7808297f2520b26a0392cd81ace83883ddd1a6a86ef048121364",
      "Nickname": "WeFilmchain",
      "Url": "www.wefilmchain.com",
      "Location": 1,
      "Active": 1,
      "Votes": "2459889.19718379",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 369749,
      "Cancelheight": 0,
      "Inactiveheight": 425829,
      "Illegalheight": 0,
      "Index": 2,
      "Reward": "1125.73452487",
      "EstRewardPerYear": "5155.58462245"
    },
    {
      "Producer_public_key": "0368044f3b3582000597d40c9293ea894237a88b2cd55f79a18193399937d22664",
      "Value": "2198600.89396518",
      "Address": "EdgCNGmt3mNL76Xq9NzPs2EucJenHbm8t5",
      "Rank": 2,
      "Ownerpublickey": "0368044f3b3582000597d40c9293ea894237a88b2cd55f79a18193399937d22664",
      "Nodepublickey": "029930b7feb8748c6bd5711116da2c378e18b4256c24f60f92ec9d398c8caf0e8e",
      "Nickname": "韩锋/SunnyFengHan",
      "Url": "http://sunnyfenghan.com",
      "Location": 1001,
      "Active": 1,
      "Votes": "2309523.12237114",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 367683,
      "Cancelheight": 0,
      "Inactiveheight": 408476,
      "Illegalheight": 0,
      "Index": 3,
      "Reward": "1102.35306636",
      "EstRewardPerYear": "5113.12797655"
    },
    {
      "Producer_public_key": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
      "Value": "2138679.58262161",
      "Address": "EcLgEzkCM9YgNqzkXXTDVcxpYwtXzbaJJg",
      "Rank": 3,
      "Ownerpublickey": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
      "Nodepublickey": "029dd934cf86e1fa22247ebde09fd8734ab24f49e3a3fde955ab24456551cd33bf",
      "Nickname": "Elephant Wallet",
      "Url": "https://elephantWallet.app",
      "Location": 65,
      "Active": 1,
      "Votes": "2564329.29188422",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 360145,
      "Cancelheight": 0,
      "Inactiveheight": 0,
      "Illegalheight": 0,
      "Index": 0,
      "Reward": "1098.33586312",
      "EstRewardPerYear": "5061.23155593"
    },
    {
      "Producer_public_key": "032459feb52daadef9d6336386bd962c4ca28077c54bda35c83b9430fc9ce7e049",
      "Value": "2042420.03140135",
      "Address": "EfUmDNrcXntkZBWUcnoQ5mrscvrH7VRsC5",
      "Rank": 4,
      "Ownerpublickey": "032459feb52daadef9d6336386bd962c4ca28077c54bda35c83b9430fc9ce7e049",
      "Nodepublickey": "02e102fdf5ed1697af88330842a1bb89128dbcdfb842feb8e1641838457fb67f06",
      "Nickname": "AnyPeer",
      "Url": "https://github.com/anyxxx/AnyPeer",
      "Location": 852,
      "Active": 1,
      "Votes": "2521230.14313134",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 369329,
      "Cancelheight": 0,
      "Inactiveheight": 0,
      "Illegalheight": 0,
      "Index": 1,
      "Reward": "1064.17536183",
      "EstRewardPerYear": "4977.86345122"
    }......

> https://api-wallet-ela.elastos.org/api/1/dpos/rank/height/999999
>> {
  "result": [
    {
      "Producer_public_key": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
      "Value": "2564329.29188422",
      "Address": "EcLgEzkCM9YgNqzkXXTDVcxpYwtXzbaJJg",
      "Rank": 1,
      "Ownerpublickey": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
      "Nodepublickey": "029dd934cf86e1fa22247ebde09fd8734ab24f49e3a3fde955ab24456551cd33bf",
      "Nickname": "Elephant Wallet",
      "Url": "https://elephantWallet.app",
      "Location": 65,
      "Active": 1,
      "Votes": "2564329.29188422",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 360145,
      "Cancelheight": 0,
      "Inactiveheight": 0,
      "Illegalheight": 0,
      "Index": 0,
      "Reward": "1098.33586312",
      "EstRewardPerYear": "11470.85671831"
    },
    {
      "Producer_public_key": "032459feb52daadef9d6336386bd962c4ca28077c54bda35c83b9430fc9ce7e049",
      "Value": "2521230.14313134",
      "Address": "EfUmDNrcXntkZBWUcnoQ5mrscvrH7VRsC5",
      "Rank": 2,
      "Ownerpublickey": "032459feb52daadef9d6336386bd962c4ca28077c54bda35c83b9430fc9ce7e049",
      "Nodepublickey": "02e102fdf5ed1697af88330842a1bb89128dbcdfb842feb8e1641838457fb67f06",
      "Nickname": "AnyPeer",
      "Url": "https://github.com/anyxxx/AnyPeer",
      "Location": 852,
      "Active": 1,
      "Votes": "2521230.14313134",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 369329,
      "Cancelheight": 0,
      "Inactiveheight": 0,
      "Illegalheight": 0,
      "Index": 1,
      "Reward": "1064.17536183",
      "EstRewardPerYear": "11331.99772114"
    },
    {
      "Producer_public_key": "0205a250b3a96ccc776604fafb84b0f8623fdfda6ec8f42c9154aa727bd95edfe2",
      "Value": "2459889.19718379",
      "Address": "EbHybMnexCbEEY4HHzxsVtZDZhzpSmShtd",
      "Rank": 3,
      "Ownerpublickey": "0205a250b3a96ccc776604fafb84b0f8623fdfda6ec8f42c9154aa727bd95edfe2",
      "Nodepublickey": "02caa563eab1cb7808297f2520b26a0392cd81ace83883ddd1a6a86ef048121364",
      "Nickname": "WeFilmchain",
      "Url": "www.wefilmchain.com",
      "Location": 1,
      "Active": 1,
      "Votes": "2459889.19718379",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 369749,
      "Cancelheight": 0,
      "Inactiveheight": 425829,
      "Illegalheight": 0,
      "Index": 2,
      "Reward": "1125.73452487",
      "EstRewardPerYear": "11134.36638766"
    },
    {
      "Producer_public_key": "0368044f3b3582000597d40c9293ea894237a88b2cd55f79a18193399937d22664",
      "Value": "2309523.12237114",
      "Address": "EdgCNGmt3mNL76Xq9NzPs2EucJenHbm8t5",
      "Rank": 4,
      "Ownerpublickey": "0368044f3b3582000597d40c9293ea894237a88b2cd55f79a18193399937d22664",
      "Nodepublickey": "029930b7feb8748c6bd5711116da2c378e18b4256c24f60f92ec9d398c8caf0e8e",
      "Nickname": "韩锋/SunnyFengHan",
      "Url": "http://sunnyfenghan.com",
      "Location": 1001,
      "Active": 1,
      "Votes": "2309523.12237114",
      "Netaddress": "",
      "State": "Active",
      "Registerheight": 367683,
      "Cancelheight": 0,
      "Inactiveheight": 408476,
      "Illegalheight": 0,
      "Index": 3,
      "Reward": "1102.35306636",
      "EstRewardPerYear": "10649.90943291"
    }......

**Comment by racollette** [comment]
Hmm. You're right. I was able to get this working after doing a fresh sync with the updated version. Not sure what was going on before.

That said, I think I did find an actual bug. See in your example how the 'Votes' quantity is identical for both block heights? For example,

https://api-wallet-ela.elastos.org/api/1/dpos/rank/height/414007

{
"Producer_public_key": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
"Value": "2138679.58262161",
"Address": "EcLgEzkCM9YgNqzkXXTDVcxpYwtXzbaJJg",
"Rank": 3,
"Ownerpublickey": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
"Nodepublickey": "029dd934cf86e1fa22247ebde09fd8734ab24f49e3a3fde955ab24456551cd33bf",
**"Nickname": "Elephant Wallet",**
"Url": "https://elephantWallet.app",
"Location": 65,
"Active": 1,
**"Votes": "2564329.29188422",**
"Netaddress": "",
"State": "Active",
"Registerheight": 360145,
"Cancelheight": 0,
"Inactiveheight": 0,
"Illegalheight": 0,
"Index": 0,
"Reward": "1098.33586312",
"EstRewardPerYear": "5061.23155593"
}

https://api-wallet-ela.elastos.org/api/1/dpos/rank/height/999999

{
"Producer_public_key": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
"Value": "2564329.29188422",
"Address": "EcLgEzkCM9YgNqzkXXTDVcxpYwtXzbaJJg",
"Rank": 1,
"Ownerpublickey": "03d55285f06683c9e5c6b5892a688affd046940c7161571611ea3a98330f72459f",
"Nodepublickey": "029dd934cf86e1fa22247ebde09fd8734ab24f49e3a3fde955ab24456551cd33bf",
**"Nickname": "Elephant Wallet",**
"Url": "https://elephantWallet.app",
"Location": 65,
"Active": 1,
**"Votes": "2564329.29188422",**
"Netaddress": "",
"State": "Active",
"Registerheight": 360145,
"Cancelheight": 0,
"Inactiveheight": 0,
"Illegalheight": 0,
"Index": 0,
"Reward": "1098.33586312",
"EstRewardPerYear": "11470.85671831"
},

That happens to be the piece of information I'm hoping to be able to retrieve historical data for but it looks to always be the most recent vote total.

**Comment by xiaomingfuckeasylife** [comment]
`Votes` shows the latest data , `Value` shows the specific height votes . @racollette

**Comment by racollette** [comment]
Ah. Didn't know that's what value meant. Probably should of noticed that. Thank you for your help. Closing this issue.
